name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '!.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '!.github/workflows/test.yml'

permissions:
  contents: read
  pull-requests: write # For test annotations in PRs

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Setup npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'

      - name: Run lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm test

  verify-dist:
    name: Verify Distribution
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Setup npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'

      - name: Build
        run: npm run build

      - name: Compare dist/
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "❌ Detected uncommitted changes in dist/ directory"
            echo "Please run 'npm run build' and commit the changes"
            git diff
            exit 1
          fi
          echo "✅ Distribution files are up to date"
